// Generated by gencpp from file hao_communication/PersonSrvResponse.msg
// DO NOT EDIT!


#ifndef HAO_COMMUNICATION_MESSAGE_PERSONSRVRESPONSE_H
#define HAO_COMMUNICATION_MESSAGE_PERSONSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hao_communication
{
template <class ContainerAllocator>
struct PersonSrvResponse_
{
  typedef PersonSrvResponse_<ContainerAllocator> Type;

  PersonSrvResponse_()
    : result()  {
    }
  PersonSrvResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hao_communication::PersonSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hao_communication::PersonSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PersonSrvResponse_

typedef ::hao_communication::PersonSrvResponse_<std::allocator<void> > PersonSrvResponse;

typedef boost::shared_ptr< ::hao_communication::PersonSrvResponse > PersonSrvResponsePtr;
typedef boost::shared_ptr< ::hao_communication::PersonSrvResponse const> PersonSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hao_communication::PersonSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hao_communication::PersonSrvResponse_<ContainerAllocator1> & lhs, const ::hao_communication::PersonSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hao_communication::PersonSrvResponse_<ContainerAllocator1> & lhs, const ::hao_communication::PersonSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hao_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hao_communication::PersonSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hao_communication::PersonSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hao_communication::PersonSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::hao_communication::PersonSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hao_communication/PersonSrvResponse";
  }

  static const char* value(const ::hao_communication::PersonSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::hao_communication::PersonSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hao_communication::PersonSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hao_communication::PersonSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAO_COMMUNICATION_MESSAGE_PERSONSRVRESPONSE_H
