// Generated by gencpp from file hao_communication/PersonSrv.msg
// DO NOT EDIT!


#ifndef HAO_COMMUNICATION_MESSAGE_PERSONSRV_H
#define HAO_COMMUNICATION_MESSAGE_PERSONSRV_H

#include <ros/service_traits.h>


#include <hao_communication/PersonSrvRequest.h>
#include <hao_communication/PersonSrvResponse.h>


namespace hao_communication
{

struct PersonSrv
{

typedef PersonSrvRequest Request;
typedef PersonSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PersonSrv
} // namespace hao_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hao_communication::PersonSrv > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::hao_communication::PersonSrv&) { return value(); }
};

template<>
struct DataType< ::hao_communication::PersonSrv > {
  static const char* value()
  {
    return "hao_communication/PersonSrv";
  }

  static const char* value(const ::hao_communication::PersonSrv&) { return value(); }
};


// service_traits::MD5Sum< ::hao_communication::PersonSrvRequest> should match
// service_traits::MD5Sum< ::hao_communication::PersonSrv >
template<>
struct MD5Sum< ::hao_communication::PersonSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hao_communication::PersonSrv >::value();
  }
  static const char* value(const ::hao_communication::PersonSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hao_communication::PersonSrvRequest> should match
// service_traits::DataType< ::hao_communication::PersonSrv >
template<>
struct DataType< ::hao_communication::PersonSrvRequest>
{
  static const char* value()
  {
    return DataType< ::hao_communication::PersonSrv >::value();
  }
  static const char* value(const ::hao_communication::PersonSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hao_communication::PersonSrvResponse> should match
// service_traits::MD5Sum< ::hao_communication::PersonSrv >
template<>
struct MD5Sum< ::hao_communication::PersonSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hao_communication::PersonSrv >::value();
  }
  static const char* value(const ::hao_communication::PersonSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hao_communication::PersonSrvResponse> should match
// service_traits::DataType< ::hao_communication::PersonSrv >
template<>
struct DataType< ::hao_communication::PersonSrvResponse>
{
  static const char* value()
  {
    return DataType< ::hao_communication::PersonSrv >::value();
  }
  static const char* value(const ::hao_communication::PersonSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HAO_COMMUNICATION_MESSAGE_PERSONSRV_H
